# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiados', '0003_preta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academia',
            old_name='num_alvara',
            new_name='num_reg',
        ),
        migrations.RenameField(
            model_name='atleta',
            old_name='num_registro',
            new_name='num_reg',
        ),
        migrations.RenameField(
            model_name='preta',
            old_name='num_registro',
            new_name='num_reg',
        ),
    ]
