# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='cartaz',
            field=models.FileField(default='/static/images/logo.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='data',
            field=models.CharField(max_length=50),
        ),
    ]
