# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(max_length=100)),
                ('faixa', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=50)),
                ('modalidade', models.CharField(max_length=50)),
                ('primeiro', models.CharField(max_length=200)),
                ('acad_primeiro', models.CharField(max_length=200)),
                ('segundo', models.CharField(max_length=200)),
                ('acad_segundo', models.CharField(max_length=200)),
                ('terceiro', models.CharField(max_length=200)),
                ('acad_terceiro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rank_campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campeonato', models.CharField(max_length=400)),
                ('est_cidade', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=50)),
                ('cartaz', models.FileField(default='/static/images/logo.jpg', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Rank_campeonato'),
        ),
    ]
